### ISSUE TITLE
Discord Invite Invalid

### ISSUE THREAD

**Issue by iamrajee** [luxonis/depthai-unity#12]
Discord link in the `Community and Support` gives the error of `Invite invalid`
![image](https://user-images.githubusercontent.com/25712145/152725042-e86f3f0f-afa8-4d67-bf7c-624892a11e34.png)
![image](https://user-images.githubusercontent.com/25712145/152724885-492f4be2-e2cb-4315-801b-2e2f06a94e1b.png)

**Comment by gespona** [comment]
Hi ! please try with this link https://discord.gg/4hGT3AFPMZ
