### ISSUE TITLE
姿态，脸部，发布后运行闪退

### ISSUE THREAD

**Issue by lister2000** [luxonis/depthai-unity#18]
BodyPose，FaceDetector，scene build and not run .     
    姿态，脸部，场景发布后运行闪退。

**Comment by gespona** [comment]
Hi ! just double checking before closing this issue. It was related to the path of the models right?

**Comment by lister2000** [comment]
you are right!
老师！謝謝您了。
..\URP_Data\Plugins\OAKForUnity\Models

**Comment by lister2000** [comment]
> Hi ! just double checking before closing this issue. It was related to the path of the models right?
You are right!
老师！謝謝您了。
..\URP_Data\Plugins\OAKForUnity\Models
