### ISSUE TITLE
Support for PoE Devices

### ISSUE THREAD

**Issue by BarnabasTakacs** [luxonis/depthai-unity#19]
Hi, 

Thank you for creating this great plugin.

I am trying to run your code in the Unity Editor on Windows. We have several PoE cameras, and they do show up and detected
with a name the same as their IPs. 
However, the demos will not show any image or connect to the cameras and crash after a few seconds.

Do you have any suggestions?

Thank you for your help in advance.
Sincerely
Barnabas Takacs

**Comment by gespona** [comment]
Hi @BarnabasTakacs ! sorry for my late response. I will test here, maybe it's just matter of update underlying depthai-core to support this device

**Comment by gespona** [comment]
@BarnabasTakacs What OAK-POE devices are you using?

**Comment by BarnabasTakacs** [comment]
Hello, No problem, thanks for getting back to me. These are the models we are using, we have 2 each
https://shop.luxonis.com/collections/beta-store/products/oak-d-pro-poe   Autofocus
https://shop.luxonis.com/collections/beta-store/products/oak-d-w-poe

**Comment by gespona** [comment]
Hi ! Cool and thx!  I have few over here .. I'm going try to reproduce the issue and come back here soon

**Comment by gespona** [comment]
Hi @BarnabasTakacs ! I can confirm that pumping depthai-unity to use depthai-core v2.17.4 fixes the issues using OAK-POE. I will try to update the repo during this week.

**Comment by BarnabasTakacs** [comment]
Sounds good, thank you for your effort. I am looking forward to testing it. B.t.w we are looking to use many-many of these cameras networked (10-50 planned), so I am very happy to see your responsiveness.

**Comment by gespona** [comment]
Hi @BarnabasTakacs . Just updated the repo.

**Comment by BarnabasTakacs** [comment]
Thank you, I can confirm it all works fine.

**Comment by BarnabasTakacs** [comment]
Hi again.

Thanks for the modifications and the bug fixes last time, it all works fine.
I have a few questions, however, that I am hoping you can address.

1. I am using 5 cameras at the moment, by directly addressing them by their device ID. All send images, but they are out of synch. I know from the Python examples that they could be synched on the host or HW. Is there a solutions you would recommend to look at?
2. I also have a need to save the camera images. You have it implemented very nicely, but the color camera texture behaves differently from the rest. By default it is a 300x300 preview image. Is there a way to get the full HD or 4K output?
3. My third comment is on the framerate. I have tried 1G ethernet and also just USB3 but in most cases the camera image
has a noticable delay even when not recording and using the 300x300 preview. Would you be able to recommend something to look deeper into to speed these up?
 
Thanks for your help in advance
Barnabas

**Comment by Erol444** [comment]
Hi @BarnabasTakacs ,
1. Syncing [docs here](https://docs.luxonis.com/projects/api/en/latest/tutorials/message_syncing/). Most customers use HW syncing option when they require sub-ms precision. If eg. 10ms latency is good enough, then timestamp syncing is ok.
2. Yes, you can do that as well. If you want to capture an image every so often [check this example ](https://docs.luxonis.com/projects/api/en/latest/samples/ColorCamera/rgb_camera_control/#rgb-camera-control)and use still images by pressing `c` (potentially encode them to JPEG on-device). You could also just stream 4k `isp` output from ColorCamera node to host as well and save images/videos there.
3. What kind of delay  are you talking about (300ms or 3sec)?

Thanks, Erik
