### ISSUE TITLE
.NET Framework/.NET Core Support

### ISSUE THREAD

**Issue by noumanqaiser** [luxonis/depthai-unity#20]
Hello, I am considering using OAK-D POE cameras for an application a .NET 5.0 Windows Forms app would need to read frames/depth data from OAK D cameras. 

My question is, Is there any wrapper/Library available that could help me read image/depth information in C#, If this is possible, Any sample that would help achieve this would be greatly appreciated.

**Comment by gespona** [comment]
Hi @noumanqaiser ! You can use depthai-unity library ... at the end integration with Unity is the same scenario, as Unity use C# scripts. To read frames/depth data I'd suggest to take a look to "streams" example, that basically shows outputs from cameras and include depth.

https://github.com/luxonis/depthai-unity/blob/main/OAKForUnity/URP/Assets/Plugins/OAKForUnity/Scripts/Predefined/Streams/DaiStreams.cs
