### ISSUE TITLE
Bump to depthai-core version and unity version.

### ISSUE THREAD

**Issue by onuralpszr** [luxonis/depthai-unity#29]
Hello, I tried with latest Unity LTS version (2021.3.15f1) along with latest depthai-core version, in first I was having some problems when I switched to scene because "camera" wasn't close properly and unity crash. But if I update unity and depthai core latest version it fixes most of the problems. Except face emotion and basic ones not working. (It could be just linux isssue or something else) but in the beginning I was not able to even switch properly scene to scene. (I have OAK-D and OAK-D Lite) For tests I used mainly OAK-D device.

**Comment by gespona** [comment]
Hi @onuralpszr . Sorry for my late reply here also. In the past we had some issues with Linux, (Interaction between Unity and Depthai) Let me check again and come back you soon

**Comment by onuralpszr** [comment]
Thank you response please let me know if you need anything.

**Comment by gespona** [comment]
Hi ! I've been testing recently on Linux and now feels really more solid. According other users, with latest depthai-core and unity fixes the issue switching scenes. Thanks for your help and patience.
