### ISSUE TITLE
How can I change the prewiew resolution of the face detector scene? I change it to 600*300,but the face detector function doesn't work.

### ISSUE THREAD

**Issue by Mr-ider** [luxonis/depthai-unity#31]
How can I change the prewiew resolution of the face detector scene? I change it to 600*300,but the face detector function doesn't work.

**Comment by gespona** [comment]
Did you change the parameters inside DaiFaceDetector.cs?

**Comment by Mr-ider** [comment]
I changed it because the perspective is relatively small now, and I want to make it larger.

**Comment by gespona** [comment]
Hi ! did you changed also the image size inside the canvas?   you need to change from square image to something like 1600x800 (same aspect ratio with the new config)

**Comment by Mr-ider** [comment]
I tried, but it still doesn't work well.

Can you help me test it as I said? Thank you!

**Comment by Mr-ider** [comment]
Hi @gespona , Could you please help me give it a try? Thank you very much！

**Comment by gespona** [comment]
Hi @Mr-ider , I'm checking on my side. Notice that input shape to face detector model is 300x300, so if you want to use wide resolution, better to keep square aspect ratio, and it's needed to reshape at some point to 300x300 as input for model 

https://github.com/luxonis/depthai-unity/blob/main/src/predefined/FaceDetector.cpp

So in case you just changed the config of previewSize  probably you're getting error message (editor log) saying that 600x300 is wrong input shape for the model and face detection is not working.

Think the best approach here is try to use any preview resolution you want and use ImageManip node to resize to 300x300 and link as input to NN

**Comment by gespona** [comment]
@Mr-ider  Also notice, than preview size is more about aspect ratio than resolution itself, because crop is happening in full resolution. So in this case, probably is needed a translation between the results on streched 300x300 to non-square ratio.

**Comment by Mr-ider** [comment]
@gespona I may not know how to solve this problem as you mentioned. Our main purpose is to broaden the view of the OAK device. Is it the wrong way to change the preview resolution?

**Comment by Mr-ider** [comment]
@gespona I don't know how to use the ImageManip node you mentioned specifically. Where should I change it in Unity? Can you help me give it a try.

**Comment by Mr-ider** [comment]
@gespona The device has a large field of view, but the available range when using facial recognition is very small. I believe all developers who use facial recognition will encounter this problem, and I hope you can improve it. Thank you very much.

**Comment by gespona** [comment]
@Mr-ider Will modify the example and create a branch for you with imageManip. This node is part of the pipeline. In other words, is on the plugin side here: https://github.com/luxonis/depthai-unity/blob/main/src/predefined/FaceDetector.cpp

**Comment by Mr-ider** [comment]
Hi @gespona ，That would be great，Looking forward to it very much! Thanks again : )

**Comment by Mr-ider** [comment]
Hi @gespona , Are there any new developments?

**Comment by gespona** [comment]
Hi @Mr-ider , yes some good progress, beside the initial approach is not really working as expected. That said, imageManip is the way to do it. Here some docs and code if you want to give a try. The idea is to use 600x300 image and use imageManip tiling to split in two images 300x300 (input shape of face detector) and combine results in the larger image

https://docs.luxonis.com/projects/api/en/latest/samples/ImageManip/image_manip_tiling/#imagemanip-tiling

**Comment by gespona** [comment]
@Mr-ider check branch https://github.com/luxonis/depthai-unity/tree/face-detector-600300     in this branch face detector is using 600x300. As explained above I'm splitting in two images 300x300, using two face detectors and adding results in final 600x300. 

Notice when face is in the middle of the image, you have two face detections. With the results inside unity, it's easy to merge both bounding boxes if you want only 1 bounding box all the time.

**Comment by gespona** [comment]
@Mr-ider I just pushed another branch https://github.com/luxonis/depthai-unity/tree/face-detector-aspect-ratio with much easier solution with 1 bounding box but wide fov.

**Comment by Mr-ider** [comment]
@gespona That's great , after my testing, this has perfectly solved my problem. Thank you for your efforts in your busy schedule!

**Comment by Mr-ider** [comment]
@gespona However, I just discovered a problem where the face can be detected within a range of 600 * 300 when the field of view increases. However, when the face moves to the edge of the screen, the Cube Character position will fly far away. I haven't found the reason yet. If you have time, please take a look.

**Comment by Mr-ider** [comment]
@gespona Do you also have the situation I mentioned on your end?

**Comment by gespona** [comment]
@Mr-ider Hi, what I can see is if face is in the edge of image (left or right) and face ROI is start to stretch then there is some flick on depth, but in very tiny part of the image. Think the reason is because now using full width, when computing depth is using a small ROI but when face ROI is starting to stretch there is no buffer on the sides to keep depth compute consistent. My suggestion is you can control this inside Unity .. as flickering is happening on very tiny part of each edge .. you just can control and when face detection position is reaching that part, you can either skip, use previous depth, or simple remove that small areas ... makes sense?

**Comment by gespona** [comment]
Hi @Mr-ider ! I just updated the repo with the letterbox approach. I think this could be good default as you have all the field of view. Also I updated the way to compute depth and removed any flickering on the edge.
