### ISSUE TITLE
Enable auto focus.

### ISSUE THREAD

**Issue by Mr-ider** [luxonis/depthai-unity#32]
How can I enable auto focus？My device is OAK-D-Lite，the device suport auto focus.

**Comment by gespona** [comment]
Hi @Mr-ider , sorry for my late response here. 

https://docs.luxonis.com/projects/hardware/en/latest/pages/guides/af_ff.html?highlight=auto%20focus

To enable AF you just need to setup manualFocus to 0

config.manualFocus = 0; // 0: Autofocus

**Comment by gespona** [comment]
@Mr-ider could you confirm that worked for you?

**Comment by Mr-ider** [comment]
@gespona Sorry for just seeing your reply, this issue has been resolved. Thank you for your reply!
