### ISSUE TITLE
Setup beta branch with Unity (WINDOWS)

### ISSUE THREAD

**Issue by gespona** [luxonis/depthai-unity#5]
Follow these steps should be fine:

- Clone repository: `git clone https://github.com/luxonis/depthai-unity.git`   On Windows I'm using git bash.
- `cd depthai-unity/`
- Checkout 'beta' branch: `git checkout beta`
- Open Unity hub. 
- You need Unity 2021.2.7f
- Add unity project: "Add" button on Hub 2.x  "Open" -> "add project from disk" on Hub 3.x
- Select folder <path_repo_cloned>\OAKForUnity\URP
- In Unity open scene: Plugins\OAKForUnity\Example Scenes\Streams
- Hit play

**Comment by gespona** [comment]
@treyDavisMCC please check this steps

**Comment by treyDavisMCC** [comment]
Thank you.  It was the "checkout" step that I was missing

**Comment by gespona** [comment]
Will keep the issue open bit more just in case

**Comment by gespona** [comment]
After some time we decided to promote beta branch to main so new workflow will be between development and main branch. Going to close this ticket.
