### ISSUE TITLE
Got error when builded the project in window - This application has requested the runtime to terminate it in an unusaual way

### ISSUE THREAD

**Issue by jieguann** [luxonis/depthai-unity#58]
Hello, we have the oak-d lite and we are trying to use the body pose (from the example scene). In the Unity editor, it runs properly, but when we make a build, it crashes and who the error as below. 
<img width="332" alt="image" src="https://github.com/luxonis/depthai-unity/assets/60665347/4bc155ef-9592-4b9c-9c37-9d0f6583d4c7">

Unity version - 2021.2.7f1
OAK-D Lite, and we also tried on OAK-D Wide
Window 11

We are also aware that also happen to other examples that require AI models like face detection or face emotion.

Any idea on how to fix this?

**Comment by gespona** [comment]
Hi @jieguann 

This is known issue:

Export Unity binary

Notice when you export binary, Unity is not doing copy of models (URP/Assets/Plugin/OAKForUnity/Models)

If you export example or scene using neural model like face detector, face emotion or body pose, you need to copy models folder content to URP_Data/Plugins/OAKForUnity/Models

**Comment by jieguann** [comment]
@gespona Thanks for you reply, it works for us now.
