### ISSUE TITLE
MSVC Runtime error for the Object Detector scene

### ISSUE THREAD

**Issue by AndreiMoraru123** [luxonis/depthai-unity#65]
Hi @gespona. The Object Detector unity pipeline seems to crash after a few seconds into the feed, at least on Windows. Here is how it looks:

![image](https://github.com/user-attachments/assets/ee4fd6bb-83c5-451b-aee3-3cc1df3d6585)

Besides on main, the crash also seems to also take place with the bumped DepthAI from this PR's branch: https://github.com/luxonis/depthai-unity/pull/64

The C++ code compiles and the C# code config also seems in order. The pipeline is a bit different from the others as it uses the YOLO API instead of a basic Neural Net and also uses depth.

There are also possibly a few checks missing like a few `getPreview`s, but none of them should matter at runtime with the default config. E.g. here, before calling `toARGB`: https://github.com/luxonis/depthai-unity/blob/main/src/predefined/ObjectDetector.cpp#L337 

I did not try to run this with any debug or sanitize flags, but I'll keep looking into it. I also tried to compile this without using depth info, and it still seems to crash.

Do you think you could have a look?

I'm using:
Unity Editor 2021.3.44f1
Visual Studio 2022 (just as the generator for CMake, which is 3.30.4)
an OAK-D Lite device

**Comment by gespona** [comment]
Hi @AndreiMoraru123 Sorry for my late response here. More than happy to check. Should not be an issue to run without depth but pipeline should be setup correctly (parameters from Unity). Will check on my side and come back to you.

**Comment by gespona** [comment]
Updated code to avoid crash. Regarding object detector we have two examples now:
https://docs.luxonis.com/software/depthai/examples/tiny_yolo/
https://docs.luxonis.com/software/depthai/examples/spatial_tiny_yolo/

Will try to fuse them in one in the future, revisiting the examples to support new oak devices ;)
Closing ticker for now
