### ISSUE TITLE
OAK Wide compatibility

### ISSUE THREAD

**Issue by HPgx** [luxonis/depthai-unity#70]
Unity example scene of the man branch are crashing with OAK-D Wide cameras.
(Face detector for example)

The issue was solved in the branch [fix-letterbox-wide](https://github.com/luxonis/depthai-unity/compare/fix-letterbox-wide) but the fix has not been applied to the main branch.

Thanks

**Comment by gespona** [comment]
Hi @HPgx , you're right . Thanks for noticing. Fix in fact is pretty simple. Let me review and add support to the main branch

**Comment by gespona** [comment]
Merged into main
